<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductosTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('bp_productos')->insert([
            ['codigo' => '001', 'descripcion' => 'Café Molido 500g', 'precio_venta' => 50.00, 'precio_oferta' => 45.00, 'oferta' => 'S'],
            ['codigo' => '002', 'descripcion' => 'Aceite de Oliva 1L', 'precio_venta' => 120.00, 'precio_oferta' => 110.00, 'oferta' => 'S'],
            ['codigo' => '003', 'descripcion' => 'Arroz Integral 1kg', 'precio_venta' => 80.00, 'precio_oferta' => 70.00, 'oferta' => 'S'],
            ['codigo' => '004', 'descripcion' => 'Pan de Molde 500g', 'precio_venta' => 35.00, 'precio_oferta' => 30.00, 'oferta' => 'S'],
            ['codigo' => '005', 'descripcion' => 'Leche Descremada 1L', 'precio_venta' => 60.00, 'precio_oferta' => 55.00, 'oferta' => 'S'],
            ['codigo' => '006', 'descripcion' => 'Harina de Trigo 1kg', 'precio_venta' => 45.00, 'precio_oferta' => 40.00, 'oferta' => 'S'],
            ['codigo' => '007', 'descripcion' => 'Azúcar Blanca 1kg', 'precio_venta' => 50.00, 'precio_oferta' => 45.00, 'oferta' => 'S'],
            ['codigo' => '008', 'descripcion' => 'Jugo de Naranja 1L', 'precio_venta' => 80.00, 'precio_oferta' => 70.00, 'oferta' => 'S'],
            ['codigo' => '009', 'descripcion' => 'Cereal Integral 500g', 'precio_venta' => 95.00, 'precio_oferta' => 85.00, 'oferta' => 'S'],
            ['codigo' => '010', 'descripcion' => 'Yogurt Natural 1L', 'precio_venta' => 85.00, 'precio_oferta' => 80.00, 'oferta' => 'S'],
            ['codigo' => '011', 'descripcion' => 'Pasta Integral 500g', 'precio_venta' => 75.00, 'precio_oferta' => 65.00, 'oferta' => 'S'],
            ['codigo' => '012', 'descripcion' => 'Mermelada de Fresa 300g', 'precio_venta' => 65.00, 'precio_oferta' => 60.00, 'oferta' => 'S'],
            ['codigo' => '013', 'descripcion' => 'Queso Rallado 200g', 'precio_venta' => 90.00, 'precio_oferta' => 85.00, 'oferta' => 'S'],
            ['codigo' => '014', 'descripcion' => 'Galletas Integrales 250g', 'precio_venta' => 40.00, 'precio_oferta' => 35.00, 'oferta' => 'S'],
            ['codigo' => '015', 'descripcion' => 'Atún en Agua 170g', 'precio_venta' => 55.00, 'precio_oferta' => 50.00, 'oferta' => 'S'],
            ['codigo' => '016', 'descripcion' => 'Tomate en Lata 400g', 'precio_venta' => 30.00, 'precio_oferta' => 25.00, 'oferta' => 'S'],
            ['codigo' => '017', 'descripcion' => 'Chocolate Negro 100g', 'precio_venta' => 70.00, 'precio_oferta' => 65.00, 'oferta' => 'S'],
            ['codigo' => '018', 'descripcion' => 'Mantequilla 200g', 'precio_venta' => 45.00, 'precio_oferta' => 40.00, 'oferta' => 'S'],
            ['codigo' => '019', 'descripcion' => 'Levadura 100g', 'precio_venta' => 35.00, 'precio_oferta' => 30.00, 'oferta' => 'S'],
            ['codigo' => '020', 'descripcion' => 'Sal Marina 1kg', 'precio_venta' => 25.00, 'precio_oferta' => 20.00, 'oferta' => 'S'],
            ['codigo' => '021', 'descripcion' => 'Polvo de Hornear 250g', 'precio_venta' => 20.00, 'precio_oferta' => 18.00, 'oferta' => 'S'],
            ['codigo' => '022', 'descripcion' => 'Salsa de Soya 500ml', 'precio_venta' => 50.00, 'precio_oferta' => 45.00, 'oferta' => 'S'],
            ['codigo' => '023', 'descripcion' => 'Vino Tinto 750ml', 'precio_venta' => 150.00, 'precio_oferta' => 140.00, 'oferta' => 'S'],
            ['codigo' => '024', 'descripcion' => 'Cerveza 355ml', 'precio_venta' => 25.00, 'precio_oferta' => 22.00, 'oferta' => 'S'],
            ['codigo' => '025', 'descripcion' => 'Agua Mineral 500ml', 'precio_venta' => 15.00, 'precio_oferta' => 12.00, 'oferta' => 'S'],
            ['codigo' => '026', 'descripcion' => 'Café Instantáneo 100g', 'precio_venta' => 60.00, 'precio_oferta' => 55.00, 'oferta' => 'S'],
            ['codigo' => '027', 'descripcion' => 'Avena Integral 500g', 'precio_venta' => 40.00, 'precio_oferta' => 35.00, 'oferta' => 'S'],
            ['codigo' => '028', 'descripcion' => 'Galletas de Avena 300g', 'precio_venta' => 30.00, 'precio_oferta' => 28.00, 'oferta' => 'S'],
            ['codigo' => '029', 'descripcion' => 'Leche en Polvo 400g', 'precio_venta' => 85.00, 'precio_oferta' => 80.00, 'oferta' => 'S'],
            ['codigo' => '030', 'descripcion' => 'Cacao en Polvo 200g', 'precio_venta' => 70.00, 'precio_oferta' => 65.00, 'oferta' => 'S'],
            ['codigo' => '031', 'descripcion' => 'Té Verde 20 Bolsas', 'precio_venta' => 45.00, 'precio_oferta' => 40.00, 'oferta' => 'S'],
            ['codigo' => '032', 'descripcion' => 'Sardinas en Aceite 125g', 'precio_venta' => 55.00, 'precio_oferta' => 50.00, 'oferta' => 'S'],
            ['codigo' => '033', 'descripcion' => 'Mayonesa Light 500g', 'precio_venta' => 35.00, 'precio_oferta' => 32.00, 'oferta' => 'S'],
            ['codigo' => '034', 'descripcion' => 'Galletas de Chocolate 200g', 'precio_venta' => 30.00, 'precio_oferta' => 28.00, 'oferta' => 'S'],
            ['codigo' => '035', 'descripcion' => 'Carne de Soya 200g', 'precio_venta' => 70.00, 'precio_oferta' => 65.00, 'oferta' => 'S'],
            ['codigo' => '036', 'descripcion' => 'Lentejas 1kg', 'precio_venta' => 90.00, 'precio_oferta' => 85.00, 'oferta' => 'S'],
            ['codigo' => '037', 'descripcion' => 'Papas Fritas 150g', 'precio_venta' => 35.00, 'precio_oferta' => 32.00, 'oferta' => 'S'],
            ['codigo' => '038', 'descripcion' => 'Manteca Vegetal 500g', 'precio_venta' => 50.00, 'precio_oferta' => 45.00, 'oferta' => 'S'],
            ['codigo' => '039', 'descripcion' => 'Miel de Abeja 500g', 'precio_venta' => 95.00, 'precio_oferta' => 85.00, 'oferta' => 'S'],
            ['codigo' => '040', 'descripcion' => 'Vinagre de Manzana 500ml', 'precio_venta' => 30.00, 'precio_oferta' => 28.00, 'oferta' => 'S'],
            ['codigo' => '041', 'descripcion' => 'Pimienta Negra 100g', 'precio_venta' => 60.00, 'precio_oferta' => 55.00, 'oferta' => 'S'],
            ['codigo' => '042', 'descripcion' => 'Clavos de Olor 100g', 'precio_venta' => 45.00, 'precio_oferta' => 40.00, 'oferta' => 'S'],
            ['codigo' => '043', 'descripcion' => 'Papas Naturales 1kg', 'precio_venta' => 25.00, 'precio_oferta' => 22.00, 'oferta' => 'S'],
            ['codigo' => '044', 'descripcion' => 'Zanahorias 1kg', 'precio_venta' => 20.00, 'precio_oferta' => 18.00, 'oferta' => 'S'],
            ['codigo' => '045', 'descripcion' => 'Cebollas 1kg', 'precio_venta' => 30.00, 'precio_oferta' => 25.00, 'oferta' => 'S'],
            ['codigo' => '046', 'descripcion' => 'Ajo 250g', 'precio_venta' => 15.00, 'precio_oferta' => 12.00, 'oferta' => 'S'],
            ['codigo' => '047', 'descripcion' => 'Pimiento Verde 500g', 'precio_venta' => 25.00, 'precio_oferta' => 20.00, 'oferta' => 'S'],
            ['codigo' => '048', 'descripcion' => 'Berenjena 1kg', 'precio_venta' => 30.00, 'precio_oferta' => 28.00, 'oferta' => 'S'],
            ['codigo' => '049', 'descripcion' => 'Pepino 1kg', 'precio_venta' => 20.00, 'precio_oferta' => 18.00, 'oferta' => 'S'],
            ['codigo' => '050', 'descripcion' => 'Plátanos 1kg', 'precio_venta' => 30.00, 'precio_oferta' => 28.00, 'oferta' => 'S'],
            ['codigo' => '051', 'descripcion' => 'Huevos de Gallina 12 Unidades', 'precio_venta' => 55.00, 'precio_oferta' => 50.00, 'oferta' => 'S'],
            ['codigo' => '052', 'descripcion' => 'Manteca de Cacao 200g', 'precio_venta' => 75.00, 'precio_oferta' => 70.00, 'oferta' => 'S'],
            ['codigo' => '053', 'descripcion' => 'Gelatina de Fresa 85g', 'precio_venta' => 20.00, 'precio_oferta' => 18.00, 'oferta' => 'S'],
            ['codigo' => '054', 'descripcion' => 'Helado de Vainilla 500ml', 'precio_venta' => 60.00, 'precio_oferta' => 55.00, 'oferta' => 'S'],
            ['codigo' => '055', 'descripcion' => 'Refresco de Cola 1.5L', 'precio_venta' => 30.00, 'precio_oferta' => 28.00, 'oferta' => 'S'],
            ['codigo' => '056', 'descripcion' => 'Cereal de Maíz 500g', 'precio_venta' => 70.00, 'precio_oferta' => 65.00, 'oferta' => 'S'],
            ['codigo' => '057', 'descripcion' => 'Galletas Dulces 300g', 'precio_venta' => 40.00, 'precio_oferta' => 35.00, 'oferta' => 'S'],
            ['codigo' => '058', 'descripcion' => 'Salchichas de Pollo 500g', 'precio_venta' => 85.00, 'precio_oferta' => 80.00, 'oferta' => 'S'],
            ['codigo' => '059', 'descripcion' => 'Filete de Tilapia 1kg', 'precio_venta' => 150.00, 'precio_oferta' => 140.00, 'oferta' => 'S'],
            ['codigo' => '060', 'descripcion' => 'Leche de Almendras 1L', 'precio_venta' => 75.00, 'precio_oferta' => 70.00, 'oferta' => 'S'],
            ['codigo' => '061', 'descripcion' => 'Pasta de Tomate 350g', 'precio_venta' => 35.00, 'precio_oferta' => 32.00, 'oferta' => 'S'],
            ['codigo' => '062', 'descripcion' => 'Jamón de Pavo 500g', 'precio_venta' => 95.00, 'precio_oferta' => 85.00, 'oferta' => 'S'],
            ['codigo' => '063', 'descripcion' => 'Queso Mozzarella 500g', 'precio_venta' => 120.00, 'precio_oferta' => 110.00, 'oferta' => 'S'],
            ['codigo' => '064', 'descripcion' => 'Helado de Chocolate 1L', 'precio_venta' => 85.00, 'precio_oferta' => 80.00, 'oferta' => 'S'],
            ['codigo' => '065', 'descripcion' => 'Pan Integral 500g', 'precio_venta' => 55.00, 'precio_oferta' => 50.00, 'oferta' => 'S'],
            ['codigo' => '066', 'descripcion' => 'Papas Criollas 1kg', 'precio_venta' => 35.00, 'precio_oferta' => 30.00, 'oferta' => 'S'],
            ['codigo' => '067', 'descripcion' => 'Galletas de Arroz 200g', 'precio_venta' => 25.00, 'precio_oferta' => 22.00, 'oferta' => 'S'],
            ['codigo' => '068', 'descripcion' => 'Cebolla Morada 1kg', 'precio_venta' => 45.00, 'precio_oferta' => 40.00, 'oferta' => 'S'],
            ['codigo' => '069', 'descripcion' => 'Tomate Cherry 250g', 'precio_venta' => 30.00, 'precio_oferta' => 28.00, 'oferta' => 'S'],
            ['codigo' => '070', 'descripcion' => 'Espinacas Frescas 250g', 'precio_venta' => 40.00, 'precio_oferta' => 35.00, 'oferta' => 'S'],
            ['codigo' => '071', 'descripcion' => 'Pepinillos en Vinagre 350g', 'precio_venta' => 35.00, 'precio_oferta' => 30.00, 'oferta' => 'S'],
            ['codigo' => '072', 'descripcion' => 'Manzana Verde 1kg', 'precio_venta' => 50.00, 'precio_oferta' => 45.00, 'oferta' => 'S'],
            ['codigo' => '073', 'descripcion' => 'Fresas 500g', 'precio_venta' => 60.00, 'precio_oferta' => 55.00, 'oferta' => 'S'],
            ['codigo' => '074', 'descripcion' => 'Uvas Rojas 1kg', 'precio_venta' => 85.00, 'precio_oferta' => 80.00, 'oferta' => 'S'],
            ['codigo' => '075', 'descripcion' => 'Limones 1kg', 'precio_venta' => 25.00, 'precio_oferta' => 20.00, 'oferta' => 'S'],
            ['codigo' => '076', 'descripcion' => 'Naranjas 1kg', 'precio_venta' => 35.00, 'precio_oferta' => 30.00, 'oferta' => 'S'],
            ['codigo' => '077', 'descripcion' => 'Carne de Res 1kg', 'precio_venta' => 180.00, 'precio_oferta' => 170.00, 'oferta' => 'S'],
            ['codigo' => '078', 'descripcion' => 'Carne de Cerdo 1kg', 'precio_venta' => 160.00, 'precio_oferta' => 150.00, 'oferta' => 'S'],
            ['codigo' => '079', 'descripcion' => 'Pollo Entero 1kg', 'precio_venta' => 120.00, 'precio_oferta' => 110.00, 'oferta' => 'S'],
            ['codigo' => '080', 'descripcion' => 'Pescado Congelado 1kg', 'precio_venta' => 135.00, 'precio_oferta' => 125.00, 'oferta' => 'S'],
            ['codigo' => '081', 'descripcion' => 'Camarones 500g', 'precio_venta' => 90.00, 'precio_oferta' => 85.00, 'oferta' => 'S'],
            ['codigo' => '082', 'descripcion' => 'Salchichas 500g', 'precio_venta' => 70.00, 'precio_oferta' => 65.00, 'oferta' => 'S'],
            ['codigo' => '083', 'descripcion' => 'Queso Parmesano 250g', 'precio_venta' => 95.00, 'precio_oferta' => 90.00, 'oferta' => 'S'],
            ['codigo' => '084', 'descripcion' => 'Salami 500g', 'precio_venta' => 100.00, 'precio_oferta' => 95.00, 'oferta' => 'S'],
            ['codigo' => '085', 'descripcion' => 'Chorizo 500g', 'precio_venta' => 85.00, 'precio_oferta' => 80.00, 'oferta' => 'S'],
            ['codigo' => '086', 'descripcion' => 'Habas 500g', 'precio_venta' => 50.00, 'precio_oferta' => 45.00, 'oferta' => 'S'],
            ['codigo' => '087', 'descripcion' => 'Quinoa 500g', 'precio_venta' => 75.00, 'precio_oferta' => 70.00, 'oferta' => 'S'],
            ['codigo' => '088', 'descripcion' => 'Arroz Blanco 1kg', 'precio_venta' => 35.00, 'precio_oferta' => 30.00, 'oferta' => 'S'],
            ['codigo' => '089', 'descripcion' => 'Harina de Maíz 1kg', 'precio_venta' => 45.00, 'precio_oferta' => 40.00, 'oferta' => 'S'],
            ['codigo' => '090', 'descripcion' => 'Pan Blanco 500g', 'precio_venta' => 30.00, 'precio_oferta' => 28.00, 'oferta' => 'S'],
            ['codigo' => '091', 'descripcion' => 'Cereales con Chocolate 500g', 'precio_venta' => 90.00, 'precio_oferta' => 85.00, 'oferta' => 'S'],
            ['codigo' => '092', 'descripcion' => 'Galletas Saladas 250g', 'precio_venta' => 35.00, 'precio_oferta' => 32.00, 'oferta' => 'S'],
            ['codigo' => '093', 'descripcion' => 'Sopa de Verduras 500g', 'precio_venta' => 45.00, 'precio_oferta' => 40.00, 'oferta' => 'S'],
            ['codigo' => '094', 'descripcion' => 'Té Negro 20 Bolsas', 'precio_venta' => 50.00, 'precio_oferta' => 45.00, 'oferta' => 'S'],
            ['codigo' => '095', 'descripcion' => 'Café Descafeinado 250g', 'precio_venta' => 80.00, 'precio_oferta' => 75.00, 'oferta' => 'S'],
            ['codigo' => '096', 'descripcion' => 'Hojuelas de Maíz 500g', 'precio_venta' => 40.00, 'precio_oferta' => 35.00, 'oferta' => 'S'],
            ['codigo' => '097', 'descripcion' => 'Tortillas de Maíz 500g', 'precio_venta' => 30.00, 'precio_oferta' => 28.00, 'oferta' => 'S'],
            ['codigo' => '098', 'descripcion' => 'Salsa de Tomate 500g', 'precio_venta' => 40.00, 'precio_oferta' => 35.00, 'oferta' => 'S'],
            ['codigo' => '099', 'descripcion' => 'Espaguetis 500g', 'precio_venta' => 60.00, 'precio_oferta' => 55.00, 'oferta' => 'S'],
            ['codigo' => '100', 'descripcion' => 'Aceitunas Negras 500g', 'precio_venta' => 70.00, 'precio_oferta' => 65.00, 'oferta' => 'S']
        ]);
        
    }
}
